# Generated by Django 4.0.5 on 2022-06-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopitall', '0002_alter_newuser_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='formulaire',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('date', models.DateTimeField(max_length=200, null=True)),
                ('condition', models.CharField(max_length=200, null=True)),
                ('comment', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
