# Generated by Django 4.0.5 on 2022-06-25 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hopitall', '0003_formulaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulaire',
            old_name='comment',
            new_name='departement',
        ),
        migrations.RenameField(
            model_name='formulaire',
            old_name='condition',
            new_name='message',
        ),
    ]
